### ISSUE TITLE
left arrow icon is smaller than all others

### ISSUE THREAD

**Issue by Ghasak** [jbyuki/venn.nvim#30]
I am really impressed by this amazing plugin and would like to express my gratitude to all the developers involved in its creation. Your hard work is truly appreciated!

I have a small request, which isn't exactly an issue, but I hope it can be addressed. It appears that the icon for the left arrow is smaller than the other arrow icons. If possible, could this be adjusted to ensure consistency across all arrow icons?
Thank you for considering my request!

The correct one is: 
```
      ▲
    ◀   ▶
      ▼


```
instead the one you provided: 

```
◄ ▼ ▲ ►  
```
notice the difference in size of the left arrow

**Comment by jbyuki** [comment]
Thank you for opening an issue.

I think this comes down to subjectivity. Indeed the arrows used are slightly narrower instead of using the "triangle" version of it which is wider. This is what I take as a reference: [triangle](https://www.compart.com/en/unicode/U+25B6), [pointer](https://www.compart.com/en/unicode/U+25BA). 

It's already possible to override these if you prefer the others. See [here](https://github.com/jbyuki/venn.nvim/issues/13#issuecomment-1107845218).

To change it for everybody, I think it makes sense only if there is a general agreement.

**Comment by Ghasak** [comment]
Thank you for your insightful comments. I completely agree with your suggestions and will proceed with my own customization using the link you provided. I am now closing this issue. Thank you once again for your guidance, and please keep up the excellent work.
