### ISSUE TITLE
Don't change last visual selection

### ISSUE THREAD

**Issue by AckslD** [jbyuki/venn.nvim#6]
It seems `venn` changes the last visual selection. For example if I select some visual block and do `:VBox` and then `gv` then it does not select same same region anymore.

Maybe the last visual selection could be saved before drawing the box and then restored again after?

**Comment by jbyuki** [comment]
For the moment I don't see a clean way to do this. In order to restore the visual block selection I would need to modify it somehow. I see two ways.

* `nvim_feedkeys` : simulate the key presses to reselect the block. The downside to this is that it could trigger keymapping such as the issue #5 .
* modify the visual block selection registers directly ( `'<` and `'>` ). Vim has a patch which allows to do [this](https://github.com/vim/vim/commit/0306ac33a53114113825242d2) but it hasn't been ported to Neovim? At least, I can't make it work on my config.

Maybe I'm not seeing something but currently I would rather go the safe way.

**Comment by jbyuki** [comment]
I will try to see I can merge some PRs into Neovim to make it work that would great.

**Comment by jbyuki** [comment]
Could you try with the latest commit? 
I found a way which would not trigger any keymapping and reselect the latest selection with `exe "norm! ..."`.

**Comment by AckslD** [comment]
Cool, I'll try it. Maybe this it what you did but couldn't you `nvim_buf_get_mark()` to get the `<` and `>` before doing anything and then after set them by putting the cursor there using ` setpos` followed by `norm m<` and same for `>`?

**Comment by AckslD** [comment]
Can confirm that the latest commit indeed works for me :+1:

**Comment by jbyuki** [comment]
> Cool, I'll try it. Maybe this it what you did but couldn't you `nvim_buf_get_mark()` to get the `<` and `>` before doing anything and then after set them by putting the cursor there using ` setpos` followed by `norm m<` and same for `>`?

This would work I think, assuming the column is corrected because `setpos` is byte based and all the multi-bytes characters which `venn` insert it will shift the column position. This could be another way.
