### ISSUE TITLE
fix(README): clarify keymaps be configured by user

### ISSUE THREAD

**Issue by matu3ba** [jbyuki/venn.nvim#9]
1. Calling keymaps needs (as of writing) global lua functions
2. sumneko lsp suggests capital letters for global functions
3. Its unclear why _G.function is used. Does it have performance advantages or do you do metatable stuff with those functions?
4. A sentence that this is suppsed to be configured by the user.

Meta: Can you make example configs or video for 1.debugger, ~~2.how to log stuff in lua with plenary, 3. repl things~~?

Meta2: Is nvim-luadev the best option as lua repl or could this be combined with the debugger somehow?

<details> 
my code

```
Toggle_venn = function()
    local venn_enabled = vim.inspect(vim.b.venn_enabled)
    if(venn_enabled == "nil") then
        vim.b.venn_enabled = true
        vim.cmd[[setlocal ve=all]]
        -- draw a line on HJKL keystokes
        vim.api.nvim_buf_set_keymap(0, "n", "J", "<C-v>j:VBox<cr>", {noremap = true})
        vim.api.nvim_buf_set_keymap(0, "n", "K", "<C-v>k:VBox<cr>", {noremap = true})
        vim.api.nvim_buf_set_keymap(0, "n", "L", "<C-v>l:VBox<cr>", {noremap = true})
        vim.api.nvim_buf_set_keymap(0, "n", "H", "<C-v>h:VBox<cr>", {noremap = true})
        -- draw a box by pressing "f" with visual selection
        vim.api.nvim_buf_set_keymap(0, "v", "f", ":VBox<cr>", {noremap = true})
    else
        vim.cmd[[setlocal ve=]]
        vim.cmd[[mapclear <buffer>]]
        vim.b.venn_enabled = nil
    end
end
map('n', '<leader>v', ":lua Toggle_venn()<cr>", opts)
```

</details>

**Comment by jbyuki** [comment]
1. Correct
2. Sure, let's rename it. 
3. Lua functions are global by default. `_G` makes it explicit. See [here](https://github.com/tamago324/lir.nvim#configuration), they use the same convention. There are functionally equivalent.
4. Sure, let's add it. Any help is welcome really.

Meta: Are you referring to [one-small-step-for-vimkind](https://github.com/jbyuki/one-small-step-for-vimkind)? You can find something [here](https://github.com/jbyuki/one-small-step-for-vimkind/issues/7#issuecomment-925273710) If you want a commented video, I have no plans to really make one, osv is really niche in my opinion.

Meta2: I've never used nvim-luadev. You can use the REPL inside nvim-dap theorically. Although I never use it. With osv, it's possible, but assignements don't work. Usually writing in a file and using `luafile %` is the best for me. Personnally, I use my other plugin [dash.nvim](https://github.com/jbyuki/dash.nvim), which ensures me that my neovim does not freeze in case of a lua infinite loop. I would suggest to build your own setup for executing lua because it's so common if you do neovim lua development.
